import {
  Wallet,
  Landmark,
  Building2,
  PiggyBank,
  CreditCard,
  Smartphone,
  Globe,
  Banknote,
  Coins,
  Vault,
  Briefcase,
  TrendingUp,
  PlusCircle,
  Home,
  Utensils,
  Car,
  HeartPulse,
  GraduationCap,
  PartyPopper,
  ShoppingBag,
  Repeat,
  MoreHorizontal,
  ArrowLeftRight,
  Tag,
  Folder,
  Target,
  HandCoins,
  Building,
  Fuel,
  Plane,
  Gift,
  Baby,
  Dog,
  Shirt,
  Wrench,
  Gamepad2,
  Wifi,
  Phone,
  Zap,
  Droplet,
  type LucideIcon,
} from "lucide-react"

export const ICON_REGISTRY: Record<string, LucideIcon> = {
  wallet: Wallet,
  landmark: Landmark,
  "building-2": Building2,
  building: Building,
  "piggy-bank": PiggyBank,
  "credit-card": CreditCard,
  smartphone: Smartphone,
  globe: Globe,
  banknote: Banknote,
  coins: Coins,
  vault: Vault,
  briefcase: Briefcase,
  "trending-up": TrendingUp,
  "plus-circle": PlusCircle,
  home: Home,
  utensils: Utensils,
  car: Car,
  "heart-pulse": HeartPulse,
  "graduation-cap": GraduationCap,
  "party-popper": PartyPopper,
  "shopping-bag": ShoppingBag,
  repeat: Repeat,
  "more-horizontal": MoreHorizontal,
  "arrow-left-right": ArrowLeftRight,
  tag: Tag,
  folder: Folder,
  target: Target,
  "hand-coins": HandCoins,
  fuel: Fuel,
  plane: Plane,
  gift: Gift,
  baby: Baby,
  dog: Dog,
  shirt: Shirt,
  wrench: Wrench,
  "gamepad-2": Gamepad2,
  wifi: Wifi,
  phone: Phone,
  zap: Zap,
  droplet: Droplet,
}

export const DEFAULT_ICON = "tag"

export function getIcon(name: string | null | undefined): LucideIcon {
  return ICON_REGISTRY[name ?? ""] ?? ICON_REGISTRY[DEFAULT_ICON]
}

export const ACCOUNT_ICON_OPTIONS = [
  "wallet",
  "landmark",
  "building-2",
  "piggy-bank",
  "credit-card",
  "smartphone",
  "globe",
  "banknote",
  "coins",
  "vault",
  "briefcase",
  "trending-up",
]

export const CATEGORY_ICON_OPTIONS = [
  "banknote",
  "briefcase",
  "trending-up",
  "plus-circle",
  "home",
  "utensils",
  "car",
  "heart-pulse",
  "graduation-cap",
  "party-popper",
  "shopping-bag",
  "repeat",
  "arrow-left-right",
  "tag",
  "folder",
  "target",
  "hand-coins",
  "fuel",
  "plane",
  "gift",
  "baby",
  "dog",
  "shirt",
  "wrench",
  "gamepad-2",
  "wifi",
  "phone",
  "zap",
  "droplet",
  "more-horizontal",
]
